name: Build and deploy Node.js apps to Azure Web App - NoumeaBnB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Handle Back-End
      - name: npm install, build, and test (Back-End)
        run: |
          cd Noumea-Back-End
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip Back-End artifact for deployment
        run: |
          cd Noumea-Back-End
          zip -r Noumea-Back-End.zip .

      - name: Upload Back-End artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: back-end-app
          path: Noumea-Back-End/Noumea-Back-End.zip

      # Handle Front-End
      - name: npm install, build, and test (Front-End)
        run: |
          cd noumea-front-end
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip Front-End artifact for deployment
        run: |
          cd noumea-front-end
          zip -r noumea-front-end.zip build/

      - name: Upload Front-End artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: front-end-app
          path: noumea-front-end/noumea-front-end.zip

      # Deploy Back-End
      - name: Download and Deploy Back-End to Azure Web App
        run: |
          unzip Noumea-Back-End.zip
          # Add Azure CLI commands to deploy the back-end project

      # Deploy Front-End
      - name: Download and Deploy Front-End to Azure Web App
        run: |
          unzip noumea-front-end.zip
          # Add Azure CLI commands to deploy the front-end project

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FAEDA0D3954B4773BC066CF501671B01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0522557153254EFFB86C9E247F57FB4E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_89766382989148C883B7B0F378675940 }}

      - name: 'Deploy to Azure Web App (Back-End)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'noumeaBnB-backend'
          slot-name: 'Production'
          package: Noumea-Back-End

      - name: 'Deploy to Azure Web App (Front-End)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'noumeaBnB-frontend'
          slot-name: 'Production'
          package: noumea-front-end
